name: Manual Deploy Release to WordPress.org
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to deploy'
        required: true
        type: string
        default: '' 
jobs:
  tag:
    name: New tag
    runs-on: ubuntu-latest
    steps:
    - name: Install Subversion
      run: sudo apt-get update && sudo apt-get install -y subversion
    - name: Checkout code
    - uses: actions/checkout@4
      with:
        tag: ${{ github.event.inputs.tag }}
    - name: WordPress Plugin Deploy
      uses: 10up/action-wordpress-plugin-deploy@stable
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
