name: Manual plugin asset/readme update
on:
  workflow_dispatch:

jobs:
  trunk:
    name: Push to trunk
    runs-on: ubuntu-latest
    permissions:
      attestations: write
      contents: read
      id-token: write
    steps:
      - name: Install Subversion
        run: sudo apt-get update && sudo apt-get install -y subversion
      - uses: actions/checkout@master
      - name: WordPress.org plugin asset/readme update
        uses: 10up/action-wordpress-plugin-asset-update@stable
        env:
          IGNORE_OTHER_FILES: true
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
